name: Feature Request
description: Suggest a new feature or improvement
type: Feature
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for Multik? We'd love to hear it!

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What is your use-case?
      placeholder: "I need to ... but currently ..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you think this could work? API sketch or pseudocode welcome.
      render: kotlin
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives or workarounds
      description: Are there other ways to achieve this today?
    validations:
      required: false